### ISSUE TITLE
[BUG] Get KeyError: 'props' when trying to run Summary()

### ISSUE THREAD

**Issue by johncoxon** [outside-edge/python-espncricinfo#44]
When I run the following code, I get the traceback below.
```
>>> from espncricinfo.summary import Summary
>>> s = Summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/John/opt/anaconda3/lib/python3.7/site-packages/espncricinfo/summary.py", line 12, in __init__
    self.match_ids = self._match_ids()
  File "/Users/John/opt/anaconda3/lib/python3.7/site-packages/espncricinfo/summary.py", line 30, in _match_ids
    matches = [x['id'] for x in self.summary_json()['props']['pageProps']['data']['content']['leagueEvents'][0]['matchEvents']]
KeyError: 'props'
```
I'm not certain what I'm doing wrong here, can someone help me out?

**Comment by BoredCyborg** [comment]
I've created a pull request which (hopefully) should fix this issue. There may still be a NoScorecardError that needs to be handled. 
https://github.com/dwillis/python-espncricinfo/pull/45

**Comment by pshreyam** [comment]
There seems to be another KeyError with class Summary while returning match_ids

>>> from espncricinfo.summary import Summary
>>> s = Summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shreyam/Documents/repos/crichelper-discord-bot/venv/lib/python3.9/site-packages/espncricinfo/summary.py", line 12, in __init__
    self.match_ids = self._match_ids()
  File "/home/shreyam/Documents/repos/crichelper-discord-bot/venv/lib/python3.9/site-packages/espncricinfo/summary.py", line 30, in _match_ids
    matches = [x['id'] for x in self.summary_json()['props']['pageProps']['data']['content']['leagueEvents'][0]['matchEvents']]
KeyError: 'content'
